server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000


spring:
  application:
    name: sea-man-sea-picture
  # 激活本地配置文件
  profiles:
    active: local
  # 开放更大的文件上传体积
  servlet:
    multipart:
      max-file-size: 10MB
  # MySQL数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sea_man_sea_picture?serverTimezone=Asia/Shanghai
    username: root
    password: Zhaohaiwei.1
  # Redis数据库配置
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      shutdown-timeout: 5000
  # Session配置
  session:
    store-type: redis
    timeout: 2592000
    # 空间图片分表
  shardingsphere:
    datasource:
      names: sea_man_sea_picture
      sea_man_sea_picture:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sea_man_sea_picture
        username: root
        password: Zhaohaiwei.1
    rules:
      sharding:
        tables:
          picture:
            actual-data-nodes: sea_man_sea_picture.picture  # 动态分表
            table-strategy:
              standard:
                sharding-column: spaceId
                sharding-algorithm-name: picture_sharding_algorithm  # 使用自定义分片算法
        sharding-algorithms:
          picture_sharding_algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.seaman.seamanseapicturebackend.manager.sharding.PictureShardingAlgorithm
    props:
      sql-show: true # 打印实际执行的sql


# mybatis-plus配置
mybatis-plus:
  configuration:
    # 将数据库中下换线格式转为驼峰
    map-underscore-to-camel-case: false
    # 仅在开发阶段使用日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 逻辑删除字段
      logic-delete-value: 1 # 已逻辑删除
      logic-not-delete-value: 0 # 未逻辑删除
    enable-sql-runner: true # 实现能够执行sql


knife4j:
  enable: true
  openapi:
    title: 海人海图接口文档
    version: 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.seaman.seamanseapicturebackend.controller